// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Reemplaza estas credenciales con las de tu proyecto de Firebase.
  // Es ideal ejecutar 'flutterfire configure' para generar este archivo automáticamente
  // con las credenciales reales y vinculadas a tu cuenta de Firebase.
  
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR-WEB-API-KEY-HERE',
    appId: 'YOUR-WEB-APP-ID-HERE',
    messagingSenderId: 'YOUR-MESSAGING-SENDER-ID-HERE',
    projectId: 'YOUR-PROJECT-ID-HERE',
    authDomain: 'YOUR-PROJECT-ID-HERE.firebaseapp.com',
    storageBucket: 'YOUR-PROJECT-ID-HERE.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR-ANDROID-API-KEY-HERE',
    appId: 'YOUR-ANDROID-APP-ID-HERE',
    messagingSenderId: 'YOUR-MESSAGING-SENDER-ID-HERE',
    projectId: 'YOUR-PROJECT-ID-HERE',
    storageBucket: 'YOUR-PROJECT-ID-HERE.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR-IOS-API-KEY-HERE',
    appId: 'YOUR-IOS-APP-ID-HERE',
    messagingSenderId: 'YOUR-MESSAGING-SENDER-ID-HERE',
    projectId: 'YOUR-PROJECT-ID-HERE',
    storageBucket: 'YOUR-PROJECT-ID-HERE.appspot.com',
    iosBundleId: 'com.example.moviles3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR-MACOS-API-KEY-HERE',
    appId: 'YOUR-MACOS-APP-ID-HERE',
    messagingSenderId: 'YOUR-MESSAGING-SENDER-ID-HERE',
    projectId: 'YOUR-PROJECT-ID-HERE',
    storageBucket: 'YOUR-PROJECT-ID-HERE.appspot.com',
    iosBundleId: 'com.example.moviles3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR-WINDOWS-API-KEY-HERE',
    appId: 'YOUR-WINDOWS-APP-ID-HERE',
    messagingSenderId: 'YOUR-MESSAGING-SENDER-ID-HERE',
    projectId: 'YOUR-PROJECT-ID-HERE',
    authDomain: 'YOUR-PROJECT-ID-HERE.firebaseapp.com',
    storageBucket: 'YOUR-PROJECT-ID-HERE.appspot.com',
  );
}
